# Generated by Django 5.2 on 2025-05-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('delete_product_physical', 'Может физически удалять товар')]},
        ),
    ]
